### ISSUE TITLE
create connection without pairing

### ISSUE THREAD

**Issue by gaganAriel** [krishnachaitanya9/Bluetooth-Chat-Android#1]
can i create connection without pairing?

**Comment by krishnachaitanya7** [comment]
No, you cannot

**Comment by gaganAriel** [comment]
any alternative option?

**Comment by krishnachaitanya7** [comment]
Bluetooth doesn't allow it. Hence No.

**Comment by gaganAriel** [comment]
are you sure about this?

**Comment by krishnachaitanya7** [comment]
Yes

**Comment by gaganAriel** [comment]
okay thanks

**Comment by gaganAriel** [comment]
tmp = mmDevice.createInsecureRfcommSocketToServiceRecord(deviceUUID);
  tmp = mmDevice.createRfcommSocketToServiceRecord(deviceUUID);

can you tell me whats difference between both

**Comment by krishnachaitanya7** [comment]
First one doesn't employ frequency hopping and the other does AFAIK
